<?xml version="1.0"?>
<package format="2">
  <name>ducted_offboard</name>
  <version>0.1.0</version>
  <description>C++ MAVROS offboard controller for the ducted quadrotor.</description>
  <maintainer email="Ayalet030703@users.noreply.github.com">nrc</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>boost</depend>
  <depend>geometry_msgs</depend>
  <depend>mavros_msgs</depend>
  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <depend>nav_msgs</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>yaml-cpp</depend>
  <test_depend>rostest</test_depend>
</package>
