origin: [-6.0, -6.0, -1.5]
size: [12.0, 12.0, 6.0]
max_speed: 0.5
max_acceleration: 0.5
max_vertical_speed: 0.3
search:
  max_tau: 0.8
  init_max_tau: 0.8
  max_vel: 0.5
  max_acc: 0.5
  w_time: 10.0
  horizon: 1.5
  resolution_astar: 0.1
  time_resolution: 0.1
  lambda_heu: 1.0
  allocate_num: 20000
  check_num: 20
  optimistic: false
  vel_margin: 0.0
optimization:
  lambda1: 10.0
  lambda2: 5.0
  lambda3: 1.0
  lambda4: 1.0
  lambda5: 1.0
  lambda6: 1.0
  lambda7: 1.0
  lambda8: 1.0
  dist0: 0.7
  max_vel: 0.5
  max_acc: 0.5
  visib_min: 0.0
  dlmin: 0.0
  wnl: 0.0
  max_iteration_num1: 100
  max_iteration_num2: 100
  max_iteration_num3: 100
  max_iteration_num4: 100
  max_iteration_time1: 0.03
  max_iteration_time2: 0.03
  max_iteration_time3: 0.03
  max_iteration_time4: 0.03
  algorithm1: 11
  algorithm2: 11
  order: 3
