cmake_minimum_required(VERSION 3.0.2)
project(ducted_planning)
add_compile_options(-std=c++14 -O2)
find_package(catkin REQUIRED COMPONENTS roscpp geometry_msgs nav_msgs sensor_msgs std_msgs message_generation pcl_conversions)
find_package(Eigen3 REQUIRED)
find_package(PCL REQUIRED COMPONENTS common io)
find_path(NLOPT_INCLUDE_DIR nlopt.hpp REQUIRED)
find_library(NLOPT_LIBRARY nlopt REQUIRED)
add_service_files(FILES PlanPath.srv)
generate_messages(DEPENDENCIES geometry_msgs nav_msgs sensor_msgs std_msgs)
catkin_package(INCLUDE_DIRS include LIBRARIES ducted_planning_core CATKIN_DEPENDS message_runtime roscpp nav_msgs sensor_msgs geometry_msgs std_msgs)
include_directories(include vendor/path_searching/include vendor/bspline/include vendor/bspline_opt/include ${catkin_INCLUDE_DIRS} ${EIGEN3_INCLUDE_DIRS} ${PCL_INCLUDE_DIRS} ${NLOPT_INCLUDE_DIR})
add_library(ducted_planning_core src/grid.cpp vendor/path_searching/src/kinodynamic_astar.cpp vendor/bspline/src/non_uniform_bspline.cpp vendor/bspline_opt/src/bspline_optimizer.cpp)
target_link_libraries(ducted_planning_core ${catkin_LIBRARIES} ${NLOPT_LIBRARY})
add_executable(global_local_planner src/planning_node.cpp)
add_dependencies(global_local_planner ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
target_link_libraries(global_local_planner ducted_planning_core ${PCL_LIBRARIES})
if(CATKIN_ENABLE_TESTING)
 add_executable(test_planning_grid test/test_grid.cpp)
 target_link_libraries(test_planning_grid ducted_planning_core)
 add_test(NAME ducted_planning_grid COMMAND test_planning_grid)
endif()
install(TARGETS ducted_planning_core global_local_planner LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION} RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY include/ DESTINATION ${CATKIN_GLOBAL_INCLUDE_DESTINATION})
install(DIRECTORY config vendor DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
