std_msgs/Header header
geometry_msgs/Pose start
geometry_msgs/Vector3 velocity
geometry_msgs/Pose goal
sensor_msgs/PointCloud2 obstacles
geometry_msgs/Transform map_to_odom
float64 clearance
float64 minimum_z
float64 maximum_z
---
bool success
string reason
nav_msgs/Path global_path
nav_msgs/Path local_path
geometry_msgs/Point tracking_target
