cmake_minimum_required(VERSION 3.0.2)
project(ducted_localization)
find_package(catkin REQUIRED COMPONENTS rospy nav_msgs geometry_msgs sensor_msgs std_msgs std_srvs mavros_msgs tf)
catkin_python_setup()
catkin_package()
catkin_install_python(PROGRAMS scripts/global_relocalizer.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
install(FILES LICENSE.AG-TEST requirements.txt DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
install(PROGRAMS scripts/setup_python.sh DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/scripts)
if(CATKIN_ENABLE_TESTING)
  catkin_add_nosetests(test/test_localization.py)
endif()
